--Load the census data for training, testing and the live data
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','TRAINING_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/splice/census_example/data/training.data.txt',null,null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','TESTING_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/splice/census_example/data/testing.data.txt',null,null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','LIVE_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/splice/census_example/data/live.data.csv',null,null,null,null,null,-1,null, true, null);

--Fix some issues with the data
update census.TESTING_DATA set LABEL = '0'  where (census.TESTING_DATA.INCOME_BRACKET LIKE '%<=50K%');
update census.TESTING_DATA set LABEL = '1' where (census.TESTING_DATA.INCOME_BRACKET LIKE '%>50K%');

update census.TRAINING_DATA set LABEL = '0'  where (census.TRAINING_DATA.INCOME_BRACKET LIKE '%<=50K%');
update census.TRAINING_DATA set LABEL = '1' where (census.TRAINING_DATA.INCOME_BRACKET LIKE '%>50K%');

-- Insert the definitions for the MODEL, MODEL_FEATURES and MODEL_FEATURE_CROSS

insert into MODEL (MODEL_ID,NAME,DESCRIPTION) values (1,'CENSUS','Predict whether income is greater than 50,000');

insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'AGE','AGE',1,'CONTINUOUS',1,null,'INTEGER','18, 25, 30, 35, 40, 45, 50, 55, 60, 65',null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'WORKCLASS','WORKCLASS',2,'CATEGORICAL',1,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'FNLWGT','FNLWGT',3,null,null,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'EDUCATION','EDUCATION',4,'CATEGORICAL',2,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'EDUCATION_NUM','EDUCATION_NUM',5,'CONTINUOUS',2,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'MARITAL_STATUS','MARITAL_STATUS',6,'CATEGORICAL',3,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'OCCUPATION','OCCUPATION',7,'CATEGORICAL',4,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'RELATIONSHIP','RELATIONSHIP',8,'CATEGORICAL',5,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'RACE','RACE',9,'CATEGORICAL',6,'Amer-Indian-Eskimo, Asian-Pac-Islander, Black, Other, White',null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'GENDER','GENDER',10,'CATEGORICAL',7,'Female, Male',null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'CAPITAL_GAIN','CAPITAL_GAIN',11,'CONTINUOUS',3,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'CAPITAL_LOSS','CAPITAL_LOSS',12,'CONTINUOUS',4,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'HOURS_PER_WEEK','HOURS_PER_WEEK',13,'CONTINUOUS',5,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'NATIVE_COUNTRY','NATIVE_COUNTRY',14,'CATEGORICAL',8,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'INCOME_BRACKET','INCOME_BRACKET',15,null,null,null,null,null,null);
insert into MODEL_FEATURES (MODEL_ID,FEATURE_NAME,DATABASE_COLUMN_NAME,EXTRACT_SEQUENCE,MODEL_DATA_TYPE,MODEL_DATA_TYPE_EXTRACT_SEQUENCE,FEATURE_KEYS,FEATURE_BUCKET_DATA_TYPE,FEATURE_BUCKETS,IS_LABEL) values (1,'LABEL','LABEL',16,null,null,null,null,null,TRUE);

insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'EDUCATION_OCCUPATION','EDUCATION',1);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'EDUCATION_OCCUPATION','OCCUPATION',2);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'AGE_EDUCATION_OCCUPATION','AGE_BUCKETS',1);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'AGE_EDUCATION_OCCUPATION','EDUCATION',2);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'AGE_EDUCATION_OCCUPATION','OCCUPATION',3);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'COUNTRY_OCCUPATION','NATIVE_COUNTRY',1);
insert into MODEL_FEATURE_CROSS (MODEL_ID,FEATURE_CROSS_NAME,FEATURE_NAME,CROSS_SEQUENCE) values (1,'COUNTRY_OCCUPATION','OCCUPATION',2);

