CREATE SCHEMA LOGAGG;

CREATE TABLE LOGAGG.AggregateResults (
  LOGDATE   TIMESTAMP,
  PUBLISHER VARCHAR(50),
  GEO       VARCHAR(50),
  IMPS      INTEGER,
  UNIQUES   INTEGER,
  AVGBIDS   DECIMAL(10, 5)
);


