#!/usr/bin/env bash

./run-kafka-spark-streaming.sh  "$KAFKA_BROKER" $KAFKA_CONSUMER_GROUP $KAFKA_TOPIC_LIST $SPARK_BATCH_INTERVAL "$SPLICE_JDBC_URL" $TARGET_SPLICE_SCHEMA $TARGET_SPLICE_TABLE $MAX_RATE "$SPLICE_CHAR_DELIM" "$SPLICE_COLUMN_DELIM" "$SPLICE_TIME_FORMAT" "$SPLICE_DATE_FORMAT" "$SPLICE_TIMESTAMP_FORMAT" "$SPLICE_TIMESTAMP_FORMAT"
