CREATE FUNCTION propertiesFile(propertyFilename VARCHAR(200))
  RETURNS TABLE(KEY_NAME VARCHAR(100), VALUE VARCHAR(200))
LANGUAGE JAVA
PARAMETER STYLE SPLICE_JDBC_RESULT_SET
READS SQL DATA
EXTERNAL NAME 'com.splicemachine.tutorials.vti.PropertiesFileVTI.getPropertiesFileVTI';
