CREATE SCHEMA iot;
SET SCHEMA iot;

CREATE TABLE RFID (
  ASSET_NUMBER      VARCHAR(50),
  ASSET_DESCRIPTION VARCHAR(100),
  RECORDED_TIME     TIMESTAMP,
  ASSET_TYPE        VARCHAR(50),
  ASSET_LOCATION    VARCHAR(50)
);


