--Load the census data for training, testing and the live data
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','TRAINING_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/census_example/data/training.data.txt',null,null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','TESTING_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/census_example/data/testing.data.txt',null,null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'CENSUS','LIVE_DATA','AGE,WORKCLASS,FNLWGT,EDUCATION,EDUCATION_NUM,MARITAL_STATUS,OCCUPATION,RELATIONSHIP,RACE,GENDER,CAPITAL_GAIN,CAPITAL_LOSS,HOURS_PER_WEEK,NATIVE_COUNTRY,INCOME_BRACKET','/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/census_example/data/live.data.csv',null,null,null,null,null,-1,null, true, null);

--Fix some issues with the data
update census.TESTING_DATA set LABEL = '0'  where (census.TESTING_DATA.INCOME_BRACKET LIKE '%<=50K%');
update census.TESTING_DATA set LABEL = '1' where (census.TESTING_DATA.INCOME_BRACKET LIKE '%>50K%');

update census.TRAINING_DATA set LABEL = '0'  where (census.TRAINING_DATA.INCOME_BRACKET LIKE '%<=50K%');
update census.TRAINING_DATA set LABEL = '1' where (census.TRAINING_DATA.INCOME_BRACKET LIKE '%>50K%');

-- Insert the definitions for the Data Set

call SPLICE.CREATE_INITIAL_PROJECT_STRUCTURE('CENSUS','Predict whether income is greater than 50,000','CENSUS.TRAINING_DATA','CENSUS.TESTING_DATA','LABEL');

update DATASET_FEATURE_DEFINITION set FEATURE_BUCKETS='18, 25, 30, 35, 40, 45, 50, 55, 60, 65', FEATURE_BUCKET_DATA_TYPE='INTEGER'
where DATABASE_COLUMN_NAME = 'AGE';

update DATASET_FEATURE_DEFINITION set FEATURE_TYPE=null
where DATABASE_COLUMN_NAME = 'FNLWGT';

update DATASET_FEATURE_DEFINITION set FEATURE_KEYS='Amer-Indian-Eskimo, Asian-Pac-Islander, Black, Other, White'
where DATABASE_COLUMN_NAME = 'RACE';

update DATASET_FEATURE_DEFINITION set FEATURE_KEYS='Female, Male'
where DATABASE_COLUMN_NAME = 'GENDER';

update DATASET_FEATURE_DEFINITION set FEATURE_TYPE=null
where DATABASE_COLUMN_NAME = 'INCOME_BRACKET';

insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'EDUCATION_OCCUPATION','EDUCATION');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'EDUCATION_OCCUPATION','OCCUPATION');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'AGE_EDUCATION_OCCUPATION','AGE_BUCKETS');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'AGE_EDUCATION_OCCUPATION','EDUCATION');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'AGE_EDUCATION_OCCUPATION','OCCUPATION');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'COUNTRY_OCCUPATION','NATIVE_COUNTRY');
insert into DATASET_FEATURE_CROSS (DATASET_ID,FEATURE_CROSS_NAME,FEATURE_NAME) values (1,'COUNTRY_OCCUPATION','OCCUPATION');

