create view  IOT.TRAIN_AGG_1_VIEW as 
SELECT a.* , 
AVG(SENSOR_MEASURE_1) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_1, 
AVG(SENSOR_MEASURE_2) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_2, 
AVG(SENSOR_MEASURE_3) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_3, 
AVG(SENSOR_MEASURE_4) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_4, 
AVG(SENSOR_MEASURE_5) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_5, 
AVG(SENSOR_MEASURE_6) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_6, 
AVG(SENSOR_MEASURE_7) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_7, 
AVG(SENSOR_MEASURE_8) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_8, 
AVG(SENSOR_MEASURE_9) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_9, 
AVG(SENSOR_MEASURE_10) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_10, 
AVG(SENSOR_MEASURE_11) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_11, 
AVG(SENSOR_MEASURE_12) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_12, 
AVG(SENSOR_MEASURE_13) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_13, 
AVG(SENSOR_MEASURE_14) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_14, 
AVG(SENSOR_MEASURE_15) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_15, 
AVG(SENSOR_MEASURE_16) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_16, 
AVG(SENSOR_MEASURE_17) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_17, 
AVG(SENSOR_MEASURE_18) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_18, 
AVG(SENSOR_MEASURE_19) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_19, 
AVG(SENSOR_MEASURE_20) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_20, 
AVG(SENSOR_MEASURE_21) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_21
FROM IOT.TRAIN_DATA a  WHERE a.ENGINE_TYPE = 1;


create view  IOT.TEST_AGG_1_VIEW as 
SELECT a.* , 
AVG(SENSOR_MEASURE_1) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_1, 
AVG(SENSOR_MEASURE_2) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_2, 
AVG(SENSOR_MEASURE_3) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_3, 
AVG(SENSOR_MEASURE_4) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_4, 
AVG(SENSOR_MEASURE_5) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_5, 
AVG(SENSOR_MEASURE_6) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_6, 
AVG(SENSOR_MEASURE_7) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_7, 
AVG(SENSOR_MEASURE_8) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_8, 
AVG(SENSOR_MEASURE_9) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_9, 
AVG(SENSOR_MEASURE_10) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_10, 
AVG(SENSOR_MEASURE_11) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_11, 
AVG(SENSOR_MEASURE_12) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_12, 
AVG(SENSOR_MEASURE_13) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_13, 
AVG(SENSOR_MEASURE_14) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_14, 
AVG(SENSOR_MEASURE_15) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_15, 
AVG(SENSOR_MEASURE_16) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_16, 
AVG(SENSOR_MEASURE_17) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_17, 
AVG(SENSOR_MEASURE_18) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_18, 
AVG(SENSOR_MEASURE_19) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_19, 
AVG(SENSOR_MEASURE_20) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_20, 
AVG(SENSOR_MEASURE_21) OVER ( PARTITION BY ENGINE_TYPE,  UNIT ORDER BY TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_21
FROM IOT.TEST_DATA a  WHERE a.ENGINE_TYPE = 1;


create view  IOT.SENSOR_AGG_1_VIEW as 
SELECT a.* , 
AVG(SENSOR_MEASURE_1) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_1, 
AVG(SENSOR_MEASURE_2) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_2, 
AVG(SENSOR_MEASURE_3) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_3, 
AVG(SENSOR_MEASURE_4) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_4, 
AVG(SENSOR_MEASURE_5) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_5, 
AVG(SENSOR_MEASURE_6) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_6, 
AVG(SENSOR_MEASURE_7) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_7, 
AVG(SENSOR_MEASURE_8) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_8, 
AVG(SENSOR_MEASURE_9) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_9, 
AVG(SENSOR_MEASURE_10) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_10, 
AVG(SENSOR_MEASURE_11) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_11, 
AVG(SENSOR_MEASURE_12) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_12, 
AVG(SENSOR_MEASURE_13) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_13, 
AVG(SENSOR_MEASURE_14) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_14, 
AVG(SENSOR_MEASURE_15) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_15, 
AVG(SENSOR_MEASURE_16) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_16, 
AVG(SENSOR_MEASURE_17) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_17, 
AVG(SENSOR_MEASURE_18) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_18, 
AVG(SENSOR_MEASURE_19) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_19, 
AVG(SENSOR_MEASURE_20) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_20, 
AVG(SENSOR_MEASURE_21) OVER ( PARTITION BY a.ENGINE_TYPE,  a.UNIT ORDER BY a.TIME ROWS BETWEEN 4  PRECEDING AND CURRENT ROW )AS AVG_SENSOR_21
FROM IOT.SENSOR_DATA a  INNER JOIN 
IOT.TO_PROCESS_SENSOR p on  p.engine_type =a.engine_type and p.unit = a.unit and p.time= a.time
where a.engine_type =1;