set schema INSURANCE;

CALL SYSCS_UTIL.IMPORT_DATA( 'INSURANCE','TRAINING_DATA',null,'/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/insurance_example/data/training.data.txt','\t',null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'INSURANCE','TESTING_DATA',null,'/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/insurance_example/data/testing.data.txt','\t',null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'INSURANCE','LIVE_DATA',null,'/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/insurance_example/data/live.data.txt','\t',null,null,null,null,-1,null, true, null);
CALL SYSCS_UTIL.IMPORT_DATA( 'INSURANCE','LIVE_DATA_EXPECTED',null,'/Users/erindriggers/dev/workspace/tensorflow/splice-community-sample-code/tutorial-tensorflow/src/main/resources/examples/insurance_example/data/live-expected.txt','\t',null,null,null,null,-1,null, true, null);

--Insert Domain Data
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (1,'High Income expensive child');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (2,'Very Important Provincials');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (3,'High status seniors');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (4,'Affluent senior apartments');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (5,'Mixed seniors');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (6,'Career and childcare');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (7,'Dinkis (double income no kids)');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (8,'Middle class families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (9,'Modern, complete families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (10,'Stable family');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (11,'Family starters');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (12 ,'Affluent young families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (13,'Young all american family');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (14,'Junior cosmopolitan');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (15,'Senior cosmopolitans');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (16,'Students in apartments');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (17,'Fresh masters in the city');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (18,'Single youth');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (19,'Suburban youth');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (20,'Etnically diverse');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (21,'Young urban have-nots');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (22,'Mixed apartment dwellers');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (23,'Young and rising');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (24,'Young, low educated');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (25,'Young seniors in the city');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (26,'Own home elderly');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (27,'Seniors in apartments');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (28,'Residential elderly');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (29,'Porchless seniors: no front yard');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (30,'Religious elderly singles');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (31,'Low income catholics');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (32,'Mixed seniors');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (33,'Lower class large families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (34,'Large family, employed child');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (35,'Village families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (36,'Couples with teens "Married with children"');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (37,'Mixed small town dwellers');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (38,'Traditional families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (39,'Large religous families');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (40,'Large family farms');
INSERT INTO DOMAIN_CUSTOMER_SUBTYPE values (41,'Mixed rurals');

INSERT INTO DOMAIN_AVERAGE_AGE values (1,'20-30 years');
INSERT INTO DOMAIN_AVERAGE_AGE values (2,'30-40 years');
INSERT INTO DOMAIN_AVERAGE_AGE values (3,'40-50 years');
INSERT INTO DOMAIN_AVERAGE_AGE values (4,'50-60 years');
INSERT INTO DOMAIN_AVERAGE_AGE values (5,'60-70 years');
INSERT INTO DOMAIN_AVERAGE_AGE values (6,'70-80 years');

INSERT INTO DOMAIN_CUSTOMER_TYPE values (1,'Successful hedonists');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (2,'Driven Growers');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (3,'Average Family');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (4,'Career Loners');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (5,'Living well');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (6,'Cruising Seniors');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (7,'Retired and Religeous');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (8,'Family with grown ups');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (9,'Conservative families');
INSERT INTO DOMAIN_CUSTOMER_TYPE values (10,'Farmers');

INSERT INTO DOMAIN_CATHOLIC values (0,'0%');
INSERT INTO DOMAIN_CATHOLIC values (1,'1 - 10%');
INSERT INTO DOMAIN_CATHOLIC values (2,'11 - 23%');
INSERT INTO DOMAIN_CATHOLIC values (3,'24 - 36%');
INSERT INTO DOMAIN_CATHOLIC values (4,'37 - 49%');
INSERT INTO DOMAIN_CATHOLIC values (5,'50 - 62%');
INSERT INTO DOMAIN_CATHOLIC values (6,'63 - 75%');
INSERT INTO DOMAIN_CATHOLIC values (7,'76 - 88%');
INSERT INTO DOMAIN_CATHOLIC values (8,'89 - 99%');
INSERT INTO DOMAIN_CATHOLIC values (9,'100%');

INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (0,'f 0');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (1,'f 1 - 49');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (2,'f 50 - 99');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (3,'f 100 - 199');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (4,'f 200 - 499');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (5,'f 500 - 999');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (6,'f 1000 - 4999');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (7,'f 5000 - 9999');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (8,'f 10.000 - 19.999');
INSERT INTO DOMAIN_PRIVATE_PARTY_INSURANCE values (9,'f 20.000 - ?');
