-- Insert the definitions for the MODEL, MODEL_FEATURES and MODEL_FEATURE_CROSS
set schema SPLICE;

call SPLICE.CREATE_INITIAL_PROJECT_STRUCTURE('INSURANCE','Predict whether a customer has a caravan insurance policy','INSURANCE.TRAINING_DATA','INSURANCE.TESTING_DATA','NUM_MOBILE_HOME');

update DATASET_FEATURE_DEFINITION set FEATURE_TYPE=null
where DATABASE_COLUMN_NAME = 'NUM_MOBILE_HOME';


