CREATE SCHEMA movielens;
SET SCHEMA movielens;

-- This table definition corresponds to the u.data file
-- The data in this file is tab delimited
CREATE TABLE user_rating (
  user_id   INTEGER,
  movie_id  INTEGER,
  rating    INTEGER,
  create_dt BIGINT,
  PRIMARY KEY (user_id, movie_id)
);

-- This table definition corresponds to the u.item
-- The data in this file is tab delimited
CREATE TABLE movies (
  movie_id           INTEGER,
  movie_title        VARCHAR(250),
  release_date       DATE,
  video_release_date DATE,
  imdb_url           VARCHAR(250),
  unknown_genre      VARCHAR(1),
  action             VARCHAR(1),
  adventure          VARCHAR(1),
  animation          VARCHAR(1),
  childrens          VARCHAR(1),
  comedy             VARCHAR(1),
  crime              VARCHAR(1),
  documentary        VARCHAR(1),
  drama              VARCHAR(1),
  fantasy            VARCHAR(1),
  film_noir          VARCHAR(1),
  horror             VARCHAR(1),
  musical            VARCHAR(1),
  mystery            VARCHAR(1),
  romance            VARCHAR(1),
  sci_fi             VARCHAR(1),
  thriller           VARCHAR(1),
  war                VARCHAR(1),
  western            VARCHAR(1),
  PRIMARY KEY (movie_id)
);

-- This table definition corresponds to the u.genre
-- The data in that file is pipe delimited
CREATE TABLE domain_genre (
  genre    VARCHAR(50),
  genre_id INTEGER
);

-- This table definition corresponds to the u.occupation
-- The data in that file with one column - no delimiter
CREATE TABLE domain_occupations (
  occupation VARCHAR(50)
);

-- This table definition corresponds to the u.user
-- The data in that file is pipe delimited
CREATE TABLE user_demographics (
  user_id    INTEGER,
  age        INTEGER,
  gender     CHAR(1),
  occupation VARCHAR(20),
  zip_code   VARCHAR(10),
  PRIMARY KEY (user_id)
);

CREATE TABLE data_feature (
  table_name   VARCHAR(100),
  column_name  VARCHAR(100),
  data_type    VARCHAR(20),
  continuous   CHAR(1),
  discrete     CHAR(1),
  parse_method VARCHAR(100)
);

CREATE TABLE model (
  id          INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 10, INCREMENT BY 1),
  model_path  VARCHAR(1000),
  create_date TIMESTAMP
);

