/*
 * Copyright 2012 - 2016 Splice Machine, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package com.splicemachine.tutorials.tsdbanalytics.dataobjects;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;

import com.splicemachine.db.iapi.error.StandardException;
import com.splicemachine.db.iapi.types.SQLDecimal;
import com.splicemachine.db.iapi.types.SQLInteger;
import com.splicemachine.db.iapi.types.SQLTimestamp;
import com.splicemachine.db.iapi.types.SQLVarchar;
import com.splicemachine.db.impl.sql.execute.ValueRow;

/**
 * AggregationResult Object definition.
 * This is the structure Key and aggregations that will be generated by aggregating the impression logs.
 * This is the object saved to Splice table.
 *
 * @author Jyotsna Ramineni
 */
public class AggregationResult implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -2362052069851453395L;

    private Timestamp date;  // minimum of dates
    private String publisher;  // Part of the group by
    private String geo;            // part of the group by
    private Integer imps;        // sum of impressions
    private Integer uniques;    // Unique count of Users(cookie)
    private Double avgBids;        // Averge Bid

    public AggregationResult(Timestamp date, String publisher, String geo,
                             Integer imps, Integer uniques, Double avgBids) {
        super();
        this.date = date;
        this.publisher = publisher;
        this.geo = geo;
        this.imps = imps;
        this.uniques = uniques;
        this.avgBids = avgBids;
    }

    /**
     * Table definition to use when using a VTI that is an instance of a class
     *
     * @return
     */
    public static String getTableDefinition() {
        return "logdate timestamp, "
                + "publisher varchar(50), "
                + "geo varchar(50), "
                + "imps integer, "
                + "uniques integer, "
                + "avgbids decimal(10,5) ";
    }

    /**
     * Used by the VTI to build a Splice Machine compatible ResultSet
     *
     * @return
     * @throws SQLException
     * @throws StandardException
     */
    public ValueRow getRow() throws SQLException, StandardException {
        ValueRow valueRow = new ValueRow(6);
        valueRow.setColumn(1, new SQLTimestamp(this.getDate()));
        valueRow.setColumn(2, new SQLVarchar(this.getPublisher()));
        valueRow.setColumn(3, new SQLVarchar(this.getGeo()));
        valueRow.setColumn(4, new SQLInteger(Integer.valueOf(this.getImps())));
        valueRow.setColumn(5, new SQLInteger(Integer.valueOf(this.getUniques())));
        valueRow.setColumn(6, new SQLDecimal(BigDecimal.valueOf(this.getAvgBids())));
        return valueRow;
    }

    /**
     * Builds a string with the values of the instance variables
     */
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("date=[" + this.getDate() + "]\n");
        sb.append("publisher=[" + this.getPublisher() + "]\n");
        sb.append("geo=[" + this.getGeo() + "]\n");
        sb.append("imps=[" + this.getImps() + "]\n");
        sb.append("uniques=[" + this.getUniques() + "]\n");
        sb.append("avgBids=[" + this.getAvgBids() + "]\n");
        return sb.toString();
    }

    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getGeo() {
        return geo;
    }

    public void setGeo(String geo) {
        this.geo = geo;
    }

    public Integer getImps() {
        return imps;
    }

    public void setImps(Integer imps) {
        this.imps = imps;
    }

    public Integer getUniques() {
        return uniques;
    }

    public void setUniques(Integer uniques) {
        this.uniques = uniques;
    }

    public Double getAvgBids() {
        return avgBids;
    }

    public void setAvgBids(Double avgBids) {
        this.avgBids = avgBids;
    }

}
